### ISSUE TITLE
Unable to start software (Crash when launching)

### ISSUE THREAD

**Issue by Cleover** [masagrator/DeiGratiaENX#3]
The game gives an (almost instant) "Unable to start software" error when opening with the exefs/romfs patch added.

I am using v1.0.1 of the game

The game is able to launch without the exefs/romfs patch

Not sure if this has any impact on things but I'm on 18.0.0 with Atmosphere 1.7.0

**Comment by masagrator** [comment]
Just tested on 18.0.1 with Atmosphere 1.7.1, downloaded fresh game and put fresh release. Everything works fine. Seek help with your setup, but not here as mod works fine.

**Comment by Cleover** [comment]
I was able to fix it, the issue was that FileZilla was transferring the files in ASCII mode rather then binary mode which broke the patch.

https://gbatemp.net/threads/exefs-patches-for-mario-odyssey-crash-on-start-mods-with-only-romfs-modifications-do-not-crash.615141/

Just leaving this comment incase anyone else has this issue.

Cheers'
